package com.exzoost.gui.customer;
/*
 * AddSellerDialog.java
 *
 * Created on December 17, 2004, 1:59 PM
 */

import com.exzoost.database.CustomerDB;
import com.exzoost.database.SalesmanDB;
import com.exzoost.gui.helper.GuiHelper;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.Connection;
/**
 *
 * @author  knight
 */
public class AddCustomerDialog extends javax.swing.JDialog {
    private Connection conn;
    
    /** Creates new form AddSellerDialog */
    public AddCustomerDialog(java.awt.Frame parent, boolean modal, 
            JTable table, Connection conn ) {
        super(parent, modal);
        
        //must the conn reference
        this.conn = conn;
        
        //setup the gui
        initComponents();
        
        GuiHelper.setOnCenter((Window)this);
        
        //must get the table reference
        this.table = table;
        
        //setup default button
        getRootPane().setDefaultButton(OK);
    }
    
    //other constructor
    public AddCustomerDialog(java.awt.Frame parent, boolean modal, Connection conn ) {
        super(parent, modal);
        
        //must the conn reference
        this.conn = conn;
        
        //setup the gui
        initComponents();
        
        //set the dialog in center of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int vpos = dim.height / 2 - getHeight() / 2;
        int hpos = dim.width / 2 - getWidth() / 2;
        setLocation( hpos, vpos );
        
        table = null;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        BottomPanel = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        DummyTopLabel = new javax.swing.JLabel();
        LeftDummyLabel = new javax.swing.JLabel();
        RightDummyLabel = new javax.swing.JLabel();
        SellerPanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        addressTA = new javax.swing.JTextArea();
        CommentLabel = new javax.swing.JLabel();
        commentTA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Customer");
        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        BottomPanel.add(Cancel);

        OK.setText("OK");
        OK.setPreferredSize(new java.awt.Dimension(75, 25));
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        BottomPanel.add(OK);

        getContentPane().add(BottomPanel, java.awt.BorderLayout.SOUTH);

        DummyTopLabel.setText("                ");
        getContentPane().add(DummyTopLabel, java.awt.BorderLayout.NORTH);

        LeftDummyLabel.setText("     ");
        getContentPane().add(LeftDummyLabel, java.awt.BorderLayout.WEST);

        RightDummyLabel.setText("     ");
        getContentPane().add(RightDummyLabel, java.awt.BorderLayout.EAST);

        SellerPanel.setLayout(new java.awt.GridBagLayout());

        SellerPanel.setBorder(new javax.swing.border.TitledBorder(null, "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11)));
        NameLabel.setText("* Name : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        SellerPanel.add(NameLabel, gridBagConstraints);

        nameTF.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        SellerPanel.add(nameTF, gridBagConstraints);

        AddressLabel.setText("Address : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        SellerPanel.add(AddressLabel, gridBagConstraints);

        PhoneLabel.setText("Phone Number : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        SellerPanel.add(PhoneLabel, gridBagConstraints);

        phoneTF.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        SellerPanel.add(phoneTF, gridBagConstraints);

        addressTA.setColumns(12);
        addressTA.setLineWrap(true);
        addressTA.setRows(4);
        addressTA.setTabSize(4);
        addressTA.setWrapStyleWord(true);
        addressTA.setBorder(new javax.swing.border.EtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        SellerPanel.add(addressTA, gridBagConstraints);

        CommentLabel.setText("Comment : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        SellerPanel.add(CommentLabel, gridBagConstraints);

        commentTA.setColumns(16);
        commentTA.setLineWrap(true);
        commentTA.setRows(8);
        commentTA.setTabSize(4);
        commentTA.setWrapStyleWord(true);
        commentTA.setBorder(new javax.swing.border.EtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        SellerPanel.add(commentTA, gridBagConstraints);

        jLabel1.setText("Fields marked with an asterisk * are required.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        SellerPanel.add(jLabel1, gridBagConstraints);

        getContentPane().add(SellerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        //gather information from dialog text field
        String name = nameTF.getText().trim();
        String address = addressTA.getText().trim();
        String phone = phoneTF.getText().trim();
        String comment = commentTA.getText();
        
        //the name field must not be null
        if(name.equals("")) {
            JOptionPane.showMessageDialog(null,"Please insert the Name Text Field!", 
                    "Warning", JOptionPane.WARNING_MESSAGE );
            return;
        }
                        
        //must use the seller class
        CustomerDB st = new CustomerDB(conn);
        
        boolean result = false;
        if(table!=null)
            result = st.insertCustomer( table, name, address, phone, comment );
        else
            result = st.insertCustomer( name, address, phone, comment );
        
        //error inserting customer
        if(!result)
            JOptionPane.showMessageDialog(null,"Error adding customer data! See log file " +
                    "for detail!", "Warning", JOptionPane.WARNING_MESSAGE );
        
        //free the resource
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomerDialog(new javax.swing.JFrame(), true, null, null).setVisible(true);
            }
        });
    }
    
    private javax.swing.JTable table;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel CommentLabel;
    private javax.swing.JLabel DummyTopLabel;
    private javax.swing.JLabel LeftDummyLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton OK;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JLabel RightDummyLabel;
    private javax.swing.JPanel SellerPanel;
    private javax.swing.JTextArea addressTA;
    private javax.swing.JTextArea commentTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField phoneTF;
    // End of variables declaration//GEN-END:variables
    
}
