/*
 * FirstTimeWizard.java
 *
 * Created on November 2, 2004, 2:20 PM
 */

package com.exzoost.gui.login;

import com.exzoost.gui.helper.GuiHelper;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.Box;
import java.awt.Dimension;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import com.exzoost.xmlhandler.XMLHandler;

/**
 *
 * @author  knight
 */
public class FirstTimeWizard extends javax.swing.JDialog {
    
    /** Creates new form FirstTimeWizard */
    public FirstTimeWizard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        //setup the gui
        initComponents();
        
        GuiHelper.setOnCenter((Window)this);
        
        //disabled the back button
        backFirstTimeWizard.setEnabled(false);
        
        //setup the size
        setSize(500,400);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        PicturePanel = new javax.swing.JPanel();
        iconCompanyFirstTimeWizard = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        welcomeFirstTimeWizard = new javax.swing.JLabel();
        companyForm = new javax.swing.JPanel();
        labelCompanyNameFirstTimeWizard = new javax.swing.JLabel();
        textCompanyNameFirstTimeWizard = new javax.swing.JTextField();
        labelOwnerNameFirstTimeWizard = new javax.swing.JLabel();
        textOwnerNameFirstTimeWizard = new javax.swing.JTextField();
        labelCompanyAddressFirstTimeWizard = new javax.swing.JLabel();
        textCompanyAddressFirstTimeWizard = new javax.swing.JTextField();
        labelPhoneNumberFirstTimeWizard = new javax.swing.JLabel();
        textPhoneNumberFirstTimeWizard = new javax.swing.JTextField();
        labelEmailFirstTimeWizard = new javax.swing.JLabel();
        textEmailFirstTimeWizard = new javax.swing.JTextField();
        finishWizard = new javax.swing.JLabel();
        BottomPanel = new javax.swing.JPanel();
        BottomPanel.add( Box.createRigidArea( new Dimension(160,10) ) );
        backFirstTimeWizard = new javax.swing.JButton();
        nextFirstTimeWizard = new javax.swing.JButton();
        cancelFirstTimeWizard = new javax.swing.JButton();
        DummyRightLabel = new javax.swing.JLabel();
        DummyTopLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("First Time Wizard");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PicturePanel.setLayout(new java.awt.BorderLayout());

        PicturePanel.setMinimumSize(new java.awt.Dimension(128, 300));
        iconCompanyFirstTimeWizard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exzoost/images/firstTimeWizard128.png")));
        iconCompanyFirstTimeWizard.setMaximumSize(new java.awt.Dimension(128, 300));
        iconCompanyFirstTimeWizard.setMinimumSize(new java.awt.Dimension(128, 300));
        iconCompanyFirstTimeWizard.setPreferredSize(new java.awt.Dimension(170, 128));
        PicturePanel.add(iconCompanyFirstTimeWizard, java.awt.BorderLayout.CENTER);

        getContentPane().add(PicturePanel, java.awt.BorderLayout.WEST);

        MainPanel.setLayout(new java.awt.CardLayout());

        MainPanel.setMaximumSize(new java.awt.Dimension(0, 100));
        MainPanel.setMinimumSize(new java.awt.Dimension(0, 30));
        welcomeFirstTimeWizard.setText("<html>Welcome, I will assist you to create your company profile or identity. \n<br>  \nYou only need to fill one form. \n<br>\n<br>\n<br>\nClick cancel if you don't want to create any new accounts now</html>");
        MainPanel.add(welcomeFirstTimeWizard, "welcome");

        companyForm.setLayout(new java.awt.GridLayout(6, 0, 10, 20));

        companyForm.setPreferredSize(new java.awt.Dimension(300, 150));
        labelCompanyNameFirstTimeWizard.setText("Company Name       :");
        companyForm.add(labelCompanyNameFirstTimeWizard);

        textCompanyNameFirstTimeWizard.setPreferredSize(new java.awt.Dimension(4, 10));
        companyForm.add(textCompanyNameFirstTimeWizard);

        labelOwnerNameFirstTimeWizard.setText("Owner Name            :");
        companyForm.add(labelOwnerNameFirstTimeWizard);

        textOwnerNameFirstTimeWizard.setPreferredSize(new java.awt.Dimension(4, 10));
        companyForm.add(textOwnerNameFirstTimeWizard);

        labelCompanyAddressFirstTimeWizard.setText("Company Address   :");
        companyForm.add(labelCompanyAddressFirstTimeWizard);

        textCompanyAddressFirstTimeWizard.setPreferredSize(new java.awt.Dimension(4, 10));
        companyForm.add(textCompanyAddressFirstTimeWizard);

        labelPhoneNumberFirstTimeWizard.setText("Phone Number         :");
        companyForm.add(labelPhoneNumberFirstTimeWizard);

        textPhoneNumberFirstTimeWizard.setPreferredSize(new java.awt.Dimension(4, 10));
        companyForm.add(textPhoneNumberFirstTimeWizard);

        labelEmailFirstTimeWizard.setText("Email                       :");
        companyForm.add(labelEmailFirstTimeWizard);

        textEmailFirstTimeWizard.setPreferredSize(new java.awt.Dimension(4, 10));
        companyForm.add(textEmailFirstTimeWizard);

        MainPanel.add(companyForm, "company");

        finishWizard.setText("<html>\nClick 'Cancel' to abort the creation of company profile.\n<br><br>\nClick 'Back' to review the creation of company profile.\n<br><br>\nClick 'Finish' to finish the creation of company profile.\n</html>");
        MainPanel.add(finishWizard, "finish");

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        backFirstTimeWizard.setText("Back");
        backFirstTimeWizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFirstTimeWizardActionPerformed(evt);
            }
        });

        BottomPanel.add(backFirstTimeWizard);

        nextFirstTimeWizard.setText("Next");
        Dimension minSize = new Dimension(5, 100);
        Dimension prefSize = new Dimension(5, 100);
        Dimension maxSize = new Dimension(Short.MAX_VALUE, 100);
        BottomPanel.add(new Box.Filler(minSize, prefSize, maxSize));
        nextFirstTimeWizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFirstTimeWizardActionPerformed(evt);
            }
        });

        BottomPanel.add(nextFirstTimeWizard);

        cancelFirstTimeWizard.setText("Cancel");
        BottomPanel.add(new Box.Filler(minSize, prefSize, maxSize));
        cancelFirstTimeWizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFirstTimeWizardActionPerformed(evt);
            }
        });

        BottomPanel.add(cancelFirstTimeWizard);

        getContentPane().add(BottomPanel, java.awt.BorderLayout.SOUTH);

        DummyRightLabel.setText("      ");
        getContentPane().add(DummyRightLabel, java.awt.BorderLayout.EAST);

        DummyTopLabel.setText("          ");
        DummyTopLabel.setPreferredSize(new java.awt.Dimension(40, 20));
        getContentPane().add(DummyTopLabel, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void backFirstTimeWizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFirstTimeWizardActionPerformed
        // User want to review the company profile that he submit
        switch(counterFirstTimeWizard) {
            case 1: backFirstTimeWizard.setEnabled(false);
                    cl.show(MainPanel, "company");
                    break;
            case 2: cl.show(MainPanel, "company");
                    nextFirstTimeWizard.setText("Next");
                    break;
        }
        counterFirstTimeWizard--;
    }//GEN-LAST:event_backFirstTimeWizardActionPerformed

    private void cancelFirstTimeWizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFirstTimeWizardActionPerformed
        // User don't want to do this now
        dispose();
    }//GEN-LAST:event_cancelFirstTimeWizardActionPerformed

    private void nextFirstTimeWizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFirstTimeWizardActionPerformed
        //gather information from dialog text field
        String companyname = textCompanyNameFirstTimeWizard.getText().trim();
        String ownername = textOwnerNameFirstTimeWizard.getText().trim();
        String companyaddress = textCompanyAddressFirstTimeWizard.getText().trim();
        String phonenumber = textPhoneNumberFirstTimeWizard.getText().trim();
        String email = textEmailFirstTimeWizard.getText().trim();
        
        switch(counterFirstTimeWizard) {
            // First time ( when user launch the application )
            case 0: backFirstTimeWizard.setEnabled(true);
                    cl = (CardLayout)(MainPanel.getLayout());
                    cl.show(MainPanel, "company");
                    break;
            // User fill the form
            case 1: if(companyname.length()==0) {
                        JOptionPane.showMessageDialog(this,"Please fill the Name field!");
                        textCompanyNameFirstTimeWizard.requestFocusInWindow();
                    }
                    else if(ownername.length()==0) {
                        JOptionPane.showMessageDialog(this,"Please fill the Owner field!");
                        textOwnerNameFirstTimeWizard.requestFocusInWindow();
                    } 
                    else if(companyaddress.length()==0) {
                        JOptionPane.showMessageDialog(this,"Please fill the Address field!");
                        textCompanyAddressFirstTimeWizard.requestFocusInWindow();
                    }
                    else { 
                        nextFirstTimeWizard.setText("Finish");
                        cl = (CardLayout)(MainPanel.getLayout());
                        cl.show(MainPanel, "finish");
                        counterFirstTimeWizard++;
                    } 
                    counterFirstTimeWizard--;
                    break;
            // Finish & write the company profile to xml file
            case 2: new XMLHandler().companyProfile( companyname, ownername, companyaddress,
                         phonenumber, email );
                    dispose();
                    new LogOnWindow().setVisible(true);
                    break;
        }
        counterFirstTimeWizard++;
    }//GEN-LAST:event_nextFirstTimeWizardActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstTimeWizard(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    private CardLayout cl;
    private short counterFirstTimeWizard = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JLabel DummyRightLabel;
    private javax.swing.JLabel DummyTopLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PicturePanel;
    private javax.swing.JButton backFirstTimeWizard;
    private javax.swing.JButton cancelFirstTimeWizard;
    private javax.swing.JPanel companyForm;
    private javax.swing.JLabel finishWizard;
    private javax.swing.JLabel iconCompanyFirstTimeWizard;
    private javax.swing.JLabel labelCompanyAddressFirstTimeWizard;
    private javax.swing.JLabel labelCompanyNameFirstTimeWizard;
    private javax.swing.JLabel labelEmailFirstTimeWizard;
    private javax.swing.JLabel labelOwnerNameFirstTimeWizard;
    private javax.swing.JLabel labelPhoneNumberFirstTimeWizard;
    private javax.swing.JButton nextFirstTimeWizard;
    private javax.swing.JTextField textCompanyAddressFirstTimeWizard;
    private javax.swing.JTextField textCompanyNameFirstTimeWizard;
    private javax.swing.JTextField textEmailFirstTimeWizard;
    private javax.swing.JTextField textOwnerNameFirstTimeWizard;
    private javax.swing.JTextField textPhoneNumberFirstTimeWizard;
    private javax.swing.JLabel welcomeFirstTimeWizard;
    // End of variables declaration//GEN-END:variables
    
}
