/*
 * LogOnWindow.java
 *
 * Created on December 20, 2004, 8:09 PM
 */

package com.exzoost.gui.login;

import com.exzoost.database.NewConnection;
import com.exzoost.gui.helper.GuiHelper;
import com.exzoost.gui.login.AdvancedDialog;
import com.exzoost.gui.maingui.MainGUI;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStreamReader;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Graphics;
import java.util.Properties;
import com.exzoost.database.Transaction;
import java.sql.Connection;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author  knight
 */
public class LogOnWindow extends javax.swing.JFrame {
    private Properties props;
    private Connection conn = null;
    /** Creates new form LogOnWindow */
    public LogOnWindow() {
        initComponents();
        setVisible(false);
        
        GuiHelper.setOnCenter((Window)this);
        
        getRootPane().setDefaultButton(Login);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        LogOnPanel = new javax.swing.JPanel();
        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UserNameTF = new javax.swing.JTextField();
        PasswordFTF = new javax.swing.JPasswordField();
        DatabaseLabel = new javax.swing.JLabel();
        DatabaseTF = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        btnAdvanced = new javax.swing.JButton();
        ImageLogOnPanel = new javax.swing.JLabel();
        PortLabel = new javax.swing.JLabel();
        PortTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Authentification");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LogOnPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogOnPanel.setBackground(new java.awt.Color(238, 241, 220));
        LogOnPanel.setPreferredSize(new java.awt.Dimension(260, 490));
        UserNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 11));
        UserNameLabel.setText("User Name : ");
        LogOnPanel.add(UserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 20));

        PasswordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 11));
        PasswordLabel.setText("Password : ");
        LogOnPanel.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, 20));

        UserNameTF.setColumns(12);
        LogOnPanel.add(UserNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, -1));

        PasswordFTF.setColumns(12);
        LogOnPanel.add(PasswordFTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 200, 20));

        DatabaseLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 11));
        DatabaseLabel.setText("Database : ");
        LogOnPanel.add(DatabaseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 20));

        DatabaseTF.setColumns(12);
        LogOnPanel.add(DatabaseTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 200, 20));

        Login.setFont(new java.awt.Font("Verdana", 0, 10));
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exzoost/images/login.png")));
        Login.setText("Login");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Login.setBorderPainted(false);
        Login.setContentAreaFilled(false);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Login.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginPageMouseExited(evt);
            }
        });

        LogOnPanel.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 60, 60));

        Exit.setFont(new java.awt.Font("Verdana", 0, 10));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exzoost/images/deleteWorker32.png")));
        Exit.setText("Exit");
        Exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Exit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginPageMouseExited(evt);
            }
        });

        LogOnPanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 60, 60));

        btnAdvanced.setFont(new java.awt.Font("Verdana", 0, 10));
        btnAdvanced.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exzoost/images/seller32.png")));
        btnAdvanced.setText("Advanced");
        btnAdvanced.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAdvanced.setBorderPainted(false);
        btnAdvanced.setContentAreaFilled(false);
        btnAdvanced.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdvanced.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAdvanced.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvancedActionPerformed(evt);
            }
        });
        btnAdvanced.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginPageMouseExited(evt);
            }
        });

        LogOnPanel.add(btnAdvanced, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 60, 60));

        ImageLogOnPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exzoost/images/exzoost.jpg")));
        LogOnPanel.add(ImageLogOnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 200));

        PortLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 11));
        PortLabel.setText("Port : ");
        LogOnPanel.add(PortLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, 20));

        PortTF.setColumns(12);
        LogOnPanel.add(PortTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, -1));

        getContentPane().add(LogOnPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
            FileInputStream fstream = new FileInputStream(
                    System.getProperty("user.home") + "/exzoost/password.txt");
            DataInputStream in = new DataInputStream(fstream);
            BufferedReader d = new BufferedReader(new InputStreamReader(in));
            UserNameTF.setText(d.readLine());
            PasswordFTF.setText(d.readLine());
            DatabaseTF.setText(d.readLine());
            PortTF.setText(d.readLine());
        }
        catch(FileNotFoundException file_e) {
            return;
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        Login.doClick();
    }//GEN-LAST:event_formWindowOpened

    private void LoginPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPageMouseExited
        JButton e= (JButton)evt.getSource();
        e.setBorderPainted(false);
        e.setContentAreaFilled(false);
    }//GEN-LAST:event_LoginPageMouseExited

    private void LoginPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPageMouseEntered
        JButton e= (JButton)evt.getSource();
        
        e.setBorderPainted(true);
        e.setBackground(new Color(241,242,232));
        e.setContentAreaFilled(true);
    }//GEN-LAST:event_LoginPageMouseEntered

    private void btnAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvancedActionPerformed
        new AdvancedDialog(this,true).setVisible(true);
    }//GEN-LAST:event_btnAdvancedActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        if(conn!=null)
            NewConnection.closeConnection(conn);
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        //Properties
        props = new Properties();
        props.setProperty( "user", UserNameTF.getText().trim() );
        props.setProperty( "password", new String(PasswordFTF.getPassword()) );
        
        //if postgresql use different port
        String port = PortTF.getText();
        if(port.trim().equals("")) {
            port = "5432";
        }
        
        //url
        String url = "jdbc:postgresql://localhost:" + port + "/" + DatabaseTF.getText().toLowerCase().trim();
        
        //the connection
        try {
            conn = NewConnection.returnConnection( props, url );  
        }
        catch( SQLException e ) {
            JOptionPane.showMessageDialog( null, e.getMessage(), 
                    "Warning Message", JOptionPane.WARNING_MESSAGE );
        }
        
        if(conn==null){
            JOptionPane.showMessageDialog(null,"Connection failed!!","Error",JOptionPane.ERROR_MESSAGE);
            props.clear();
            PasswordFTF.setText("");
            conn=null;
            url="";
            
        }
        else{
            setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MainGUI(conn).setVisible(true);
                }
            });
            dispose();  
        }
    }//GEN-LAST:event_LoginActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatabaseLabel;
    private javax.swing.JTextField DatabaseTF;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel ImageLogOnPanel;
    private javax.swing.JPanel LogOnPanel;
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField PasswordFTF;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PortLabel;
    private javax.swing.JTextField PortTF;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameTF;
    private javax.swing.JButton btnAdvanced;
    // End of variables declaration//GEN-END:variables
    
}
