/*
 * AskSuperUserRight.java
 *
 * Created on March 19, 2005, 5:05 AM
 */

package com.exzoost.gui.maingui;

import com.exzoost.database.ManipulateDB;
import com.exzoost.gui.helper.GuiHelper;
import com.exzoost.gui.login.FileConfigurationManipulate;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.File;
import java.sql.Connection;
import javax.swing.JFileChooser;

/**
 *
 * @author  knight
 */
public class AskSuperUserRight extends javax.swing.JDialog {
    private Connection conn;
    /** Creates new form AskSuperUserRight */
    public AskSuperUserRight(java.awt.Frame parent, boolean modal, Connection conn ) {
        super(parent, modal);
        initComponents();
        this.conn = conn;
        
        GuiHelper.setOnCenter((Window)this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BottomPanel = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        RightDummyLabel = new javax.swing.JLabel();
        LeftDummyLabel = new javax.swing.JLabel();
        DummyTopLabel = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        SuperUserLB = new javax.swing.JLabel();
        SuperUserTF = new javax.swing.JTextField();
        PasswordTF = new javax.swing.JPasswordField();
        PasswordLB = new javax.swing.JLabel();
        SecurityPicture = new javax.swing.JLabel();
        PortLB = new javax.swing.JLabel();
        PortTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ask Super User Password");
        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        BottomPanel.add(Cancel);

        OK.setText("OK");
        OK.setPreferredSize(new java.awt.Dimension(75, 25));
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        BottomPanel.add(OK);

        getContentPane().add(BottomPanel, java.awt.BorderLayout.SOUTH);

        RightDummyLabel.setText("     ");
        getContentPane().add(RightDummyLabel, java.awt.BorderLayout.EAST);

        LeftDummyLabel.setText("     ");
        getContentPane().add(LeftDummyLabel, java.awt.BorderLayout.WEST);

        DummyTopLabel.setText("                ");
        getContentPane().add(DummyTopLabel, java.awt.BorderLayout.NORTH);

        MainPanel.setLayout(new java.awt.GridBagLayout());

        SuperUserLB.setText("SuperUser Name : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        MainPanel.add(SuperUserLB, gridBagConstraints);

        SuperUserTF.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 20);
        MainPanel.add(SuperUserTF, gridBagConstraints);

        PasswordTF.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 20);
        MainPanel.add(PasswordTF, gridBagConstraints);

        PasswordLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PasswordLB.setText("Password : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 0);
        MainPanel.add(PasswordLB, gridBagConstraints);

        SecurityPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exzoost/images/security64.png")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        MainPanel.add(SecurityPicture, gridBagConstraints);

        PortLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PortLB.setText("Port : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 0);
        MainPanel.add(PortLB, gridBagConstraints);

        PortTF.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 20);
        MainPanel.add(PortTF, gridBagConstraints);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        //create the file chooser
        final JFileChooser fc = new JFileChooser();
        
        //in response to button click
        int returnVal = fc.showSaveDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File exportFile = fc.getSelectedFile();
            
            ManipulateDB manipulatedb = new ManipulateDB( conn );
            
            //if postgresql use different port
            String port = PortTF.getText();
            if(port.trim().equals("")) {
                port = "5432";
            }
            
            //so the user cancel the importing data or he say "no" for importing data
            FileConfigurationManipulate filemani = new FileConfigurationManipulate();
            filemani.dummyPasswordFile( manipulatedb.getCurrentDatabase(), SuperUserTF.getText(), 
                    new String( PasswordTF.getPassword()), port );
            manipulatedb.exportDatabase(exportFile, port);
            
            filemani.returnOriginalFile();
        }
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new AskSuperUserRight(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel DummyTopLabel;
    private javax.swing.JLabel LeftDummyLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton OK;
    private javax.swing.JLabel PasswordLB;
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JLabel PortLB;
    private javax.swing.JTextField PortTF;
    private javax.swing.JLabel RightDummyLabel;
    private javax.swing.JLabel SecurityPicture;
    private javax.swing.JLabel SuperUserLB;
    private javax.swing.JTextField SuperUserTF;
    // End of variables declaration//GEN-END:variables
    
}
