/*
 * SearchInventoryDialog.java
 *
 * Created on November 14, 2004, 8:32 AM
 */

package com.exzoost.gui.maingui;

import com.exzoost.database.InventoryDB;
import com.exzoost.gui.helper.GuiHelper;
import com.exzoost.gui.maingui.MainGUI;
import com.exzoost.xmlhandler.XMLHandler;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  knight
 */
public class EditHomeDialog extends javax.swing.JDialog {
    /** Creates new form SearchInventoryDialog */
    private XMLHandler xmlhandler = new XMLHandler();
    public EditHomeDialog(java.awt.Frame parent, boolean modal ) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(OK);
        
        GuiHelper.setOnCenter((Window)this);
        
        //set up the dialog
        CompanyTF.setText( xmlhandler.elementCompanyProfile("name") );
        NameTF.setText( xmlhandler.elementCompanyProfile("owner") );
        AddressTF.setText( xmlhandler.elementCompanyProfile("address") );
        PhoneTF.setText( xmlhandler.elementCompanyProfile("phone") );
        EmailTF.setText( xmlhandler.elementCompanyProfile("email") );
        
        this.table = table;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        bottomJP = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        topJP = new javax.swing.JPanel();
        leftJP = new javax.swing.JPanel();
        rightJP = new javax.swing.JPanel();
        mainJP = new javax.swing.JPanel();
        CompanyNameLabel = new javax.swing.JLabel();
        CompanyTF = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        AddressTF = new javax.swing.JTextField();
        PhoneLabel = new javax.swing.JLabel();
        PhoneTF = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Company Profile");
        bottomJP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        bottomJP.add(Cancel);

        OK.setText("OK");
        OK.setMaximumSize(new java.awt.Dimension(69, 25));
        OK.setMinimumSize(new java.awt.Dimension(69, 25));
        OK.setPreferredSize(new java.awt.Dimension(69, 25));
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        bottomJP.add(OK);

        getContentPane().add(bottomJP, java.awt.BorderLayout.SOUTH);

        getContentPane().add(topJP, java.awt.BorderLayout.NORTH);

        getContentPane().add(leftJP, java.awt.BorderLayout.WEST);

        getContentPane().add(rightJP, java.awt.BorderLayout.EAST);

        mainJP.setLayout(new java.awt.GridBagLayout());

        mainJP.setBorder(new javax.swing.border.TitledBorder("Home"));
        CompanyNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CompanyNameLabel.setText("Company Name : ");
        CompanyNameLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(CompanyNameLabel, gridBagConstraints);

        CompanyTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(CompanyTF, gridBagConstraints);

        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NameLabel.setText("Owner Name : ");
        NameLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(NameLabel, gridBagConstraints);

        NameTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(NameTF, gridBagConstraints);

        AddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AddressLabel.setText("Address : ");
        AddressLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(AddressLabel, gridBagConstraints);

        AddressTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(AddressTF, gridBagConstraints);

        PhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PhoneLabel.setText("Phone : ");
        PhoneLabel.setMaximumSize(new java.awt.Dimension(154, 15));
        PhoneLabel.setMinimumSize(new java.awt.Dimension(154, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(PhoneLabel, gridBagConstraints);

        PhoneTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(PhoneTF, gridBagConstraints);

        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EmailLabel.setText("Email : ");
        EmailLabel.setMaximumSize(new java.awt.Dimension(154, 15));
        EmailLabel.setMinimumSize(new java.awt.Dimension(154, 15));
        EmailLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(EmailLabel, gridBagConstraints);

        EmailTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(EmailTF, gridBagConstraints);

        getContentPane().add(mainJP, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        //get data from text field
        String name = NameTF.getText().trim();
        String company = CompanyTF.getText().trim();
        String address = AddressTF.getText().trim();
        String phone = PhoneTF.getText().trim();
        String email = EmailTF.getText().trim();
        
        if(name.equals("")) {
            JOptionPane.showMessageDialog(null,"Please insert the name text field!", 
                    "Warning", JOptionPane.WARNING_MESSAGE );
            NameTF.requestFocusInWindow();
            return;
        }
        
        if(company.equals("")) {
            JOptionPane.showMessageDialog(null,"Please insert the company name text field!", 
                    "Warning", JOptionPane.WARNING_MESSAGE );
            CompanyTF.requestFocusInWindow();
            return;
        }
        
        if(address.equals("")) {
            JOptionPane.showMessageDialog(null,"Please insert the address text field!", 
                    "Warning", JOptionPane.WARNING_MESSAGE );
            AddressTF.requestFocusInWindow();
            return;
        }
        
        xmlhandler.companyProfile( company, name, address, phone, email );
                
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditHomeDialog(new javax.swing.JFrame(), true ).setVisible(true);
            }
        });
    }
    
    private javax.swing.JTable table;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTF;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel CompanyNameLabel;
    private javax.swing.JTextField CompanyTF;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton OK;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneTF;
    private javax.swing.JPanel bottomJP;
    private javax.swing.JPanel leftJP;
    private javax.swing.JPanel mainJP;
    private javax.swing.JPanel rightJP;
    private javax.swing.JPanel topJP;
    // End of variables declaration//GEN-END:variables
    
}
