/*
 * ChooseWarehouse.java
 *
 * Created on April 1, 2005, 12:39 AM
 */

package com.exzoost.gui.transactions;

import com.exzoost.database.InventoryDB;
import com.exzoost.database.Transaction;
import com.exzoost.gui.helper.GuiHelper;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.sql.Connection;

/**
 *
 * @author  knight
 */
public class ChooseWarehouse extends javax.swing.JDialog {
    private Transaction tr;
    private InventoryDB inventory;
    private Connection conn;
    private StringBuffer warehouse;
    /** Creates new form ChooseWarehouse */
    public ChooseWarehouse(java.awt.Frame parent, boolean modal, Connection conn,
            String note, StringBuffer warehouse ) {
        super(parent, modal);
        initComponents();
        
        this.warehouse = warehouse;
        
        GuiHelper.setOnCenter((Window)this);
        
        //must use the transaction class
        inventory = new InventoryDB( conn );
        inventory.initializeComboBox( WarehouseCoB, "warehouse_only" );
        
        if(note.equals("delete sale")) {
            NoteLabel.setText("<html>Where do you want to put the items if <br>you cancel the sale " +
                    "transaction?</html>");
        }
        else if(note.equals("delete purchase")) {
            NoteLabel.setText("<html>From where do you want to take the items if <br>you cancel the " +
                    "purchase transaction?</html>");
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        TopDummyLabel = new javax.swing.JPanel();
        RightDummyLabel = new javax.swing.JPanel();
        LeftDummyLabel = new javax.swing.JPanel();
        BottomPanel = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        WarehouseCoB = new javax.swing.JComboBox();
        NoteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Warehouse Dialog");
        getContentPane().add(TopDummyLabel, java.awt.BorderLayout.NORTH);

        getContentPane().add(RightDummyLabel, java.awt.BorderLayout.EAST);

        getContentPane().add(LeftDummyLabel, java.awt.BorderLayout.WEST);

        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        BottomPanel.add(Cancel);

        OK.setText("OK");
        OK.setPreferredSize(new java.awt.Dimension(75, 25));
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        BottomPanel.add(OK);

        getContentPane().add(BottomPanel, java.awt.BorderLayout.SOUTH);

        MainPanel.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        MainPanel.add(WarehouseCoB, gridBagConstraints);

        NoteLabel.setText("jLabel1");
        NoteLabel.setPreferredSize(new java.awt.Dimension(290, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        MainPanel.add(NoteLabel, gridBagConstraints);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        warehouse.replace(0, 4, "Root");
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        String warehousecob = (String)WarehouseCoB.getSelectedItem();
        warehouse.replace(0, warehousecob.length(), warehousecob );
        dispose();
    }//GEN-LAST:event_OKActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton Cancel;
    private javax.swing.JPanel LeftDummyLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NoteLabel;
    private javax.swing.JButton OK;
    private javax.swing.JPanel RightDummyLabel;
    private javax.swing.JPanel TopDummyLabel;
    private javax.swing.JComboBox WarehouseCoB;
    // End of variables declaration//GEN-END:variables
    
}
