package com.exzoost.gui.transactions;
/*
 * SaleStuffDialog.java
 *
 * Created on November 11, 2004, 6:10 PM
 */

import com.exzoost.gui.helper.GuiHelper;
import com.exzoost.gui.htmleditor.HTMLEditorManipulation;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.Window;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.Box;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableModelListener;
import javax.swing.event.TableModelEvent;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.DefaultCellEditor;
import javax.swing.JTextField;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.Properties;
import com.exzoost.database.Transaction;

/**
 *
 * @author  knight
 */
public class EditSalaryTransactionDialog extends javax.swing.JDialog {
    private Connection conn;
    private JTable table;
    private Transaction tr;
    private NumberFormat nf;
    private DateFormat df;
    private String originalinvoice;
    ResultSet uprs;
    private int rowUser = 0;
    /** Creates new form SaleStuffDialog */
    public EditSalaryTransactionDialog(java.awt.Frame parent, boolean modal, 
            JTable table, Connection conn ) {
        super(parent, modal);
        this.conn = conn;
        this.table = table;
        
        //must get help from transaction class
        tr = new Transaction( conn );
        
        //setup the gui
        initComponents();
        
        nf = NumberFormat.getCurrencyInstance( new Locale("id","id"));
        df = DateFormat.getDateInstance( DateFormat.LONG, Locale.ENGLISH );
        
        //maximize it
        //set the dialog in center of the screen and set the size
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize( new java.awt.Dimension( dim.width, dim.height - 100) );
        GuiHelper.setOnCenter((Window)this);
                
        //remove the index column
        SalaryPaymentTB.removeColumn( SalaryPaymentTB.getColumnModel().getColumn(6) );
        
        SetUpDialog();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        topJP = new javax.swing.JPanel();
        TopRightPanel = new javax.swing.JPanel();
        SalaryDateChooser = new com.toedter.calendar.JDateChooser();
        TopLeftPanel = new javax.swing.JPanel();
        InvoiceLB = new javax.swing.JLabel();
        InvoiceTF = new javax.swing.JTextField();
        rightDummyLabel = new javax.swing.JLabel();
        leftDummyLabel = new javax.swing.JLabel();
        bottomJP = new javax.swing.JPanel();
        bottomButtonJP = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        BottomPanel = new javax.swing.JPanel();
        CommentLabel = new javax.swing.JLabel();
        CommentTA = new javax.swing.JTextArea();
        EmployeeTbP = new javax.swing.JTabbedPane();
        SalaryPaymentScP = new javax.swing.JScrollPane();
        SalaryPaymentTB = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Salary Transaction Dialog");
        setModal(true);
        topJP.setLayout(new java.awt.BorderLayout());

        TopRightPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        SalaryDateChooser.setPreferredSize(new java.awt.Dimension(160, 20));
        TopRightPanel.add(SalaryDateChooser);

        topJP.add(TopRightPanel, java.awt.BorderLayout.EAST);

        TopLeftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        InvoiceLB.setText("Invoice : ");
        TopLeftPanel.add(InvoiceLB);

        InvoiceTF.setColumns(12);
        TopLeftPanel.add(InvoiceTF);

        topJP.add(TopLeftPanel, java.awt.BorderLayout.WEST);

        getContentPane().add(topJP, java.awt.BorderLayout.NORTH);

        rightDummyLabel.setText("          ");
        getContentPane().add(rightDummyLabel, java.awt.BorderLayout.EAST);

        leftDummyLabel.setText("          ");
        getContentPane().add(leftDummyLabel, java.awt.BorderLayout.WEST);

        bottomJP.setLayout(new java.awt.BorderLayout());

        bottomButtonJP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        bottomButtonJP.add(Cancel);

        OK.setText("OK");
        OK.setMaximumSize(new java.awt.Dimension(75, 25));
        OK.setMinimumSize(new java.awt.Dimension(75, 25));
        OK.setPreferredSize(new java.awt.Dimension(75, 25));
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        bottomButtonJP.add(OK);

        bottomJP.add(bottomButtonJP, java.awt.BorderLayout.SOUTH);

        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        CommentLabel.setText("Comment : ");
        BottomPanel.add(CommentLabel);

        CommentTA.setColumns(16);
        CommentTA.setRows(8);
        CommentTA.setTabSize(4);
        CommentTA.setBorder(new javax.swing.border.EtchedBorder());
        BottomPanel.add(CommentTA);

        bottomJP.add(BottomPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bottomJP, java.awt.BorderLayout.SOUTH);

        SalaryPaymentTB.setSelectionMode( ListSelectionModel.SINGLE_SELECTION );
        SalaryPaymentTB.getTableHeader().setReorderingAllowed(false);
        SalaryPaymentTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, new Integer(0), new Integer(0), new Integer(0), null, null},
                {null, null, new Integer(0), new Integer(0), new Integer(0), null, null},
                {null, null, new Integer(0), new Integer(0), new Integer(0), null, null},
                {null, null, new Integer(0), new Integer(0), new Integer(0), null, null}
            },
            new String [] {
                "Code Number", "Name", "Salary", "Salary Cut", "Salary Bonus", "Type", "Index"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SalaryPaymentTB.setColumnSelectionAllowed(true);
        SalaryPaymentTB.setSelectionBackground(new java.awt.Color(0, 204, 153));
        SalaryPaymentScP.setViewportView(SalaryPaymentTB);

        EmployeeTbP.addTab("Salary Payment", SalaryPaymentScP);

        getContentPane().add(EmployeeTbP, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        //get the information from the dialog
        String invoice = InvoiceTF.getText().trim();
        String comment = CommentTA.getText();
        
        boolean result = tr.EditSalaryTransaction(originalinvoice, invoice, 
                new java.sql.Date(SalaryDateChooser.getDate().getTime()), comment );
        
        //error editing salary payment transaction
        if(!result)
            JOptionPane.showMessageDialog(null,"Error editing salary payment transaction data! " +
                    "See log file for detail!", "Warning", JOptionPane.WARNING_MESSAGE );
                
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed
    
    private void SetUpDialog() {
        int row = table.getSelectedRow();
        
        InvoiceTF.setText( (String)table.getModel().getValueAt(row,0) );
        originalinvoice = InvoiceTF.getText();
        try {
            SalaryDateChooser.setDate( df.parse( (String)table.getModel().getValueAt(row,1) ) );
        }
        catch( java.text.ParseException e ) {
            System.out.println(e.getMessage());
        }
        CommentTA.setText( (String)table.getModel().getValueAt(row,2) );
        
        tr.InitializeSalaryEditTransactionDialog( InvoiceTF.getText(), SalaryPaymentTB );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryTransactionDialog(new javax.swing.JFrame(), true, null, null).setVisible(true);
            }
        });
    }
    
    
    private javax.swing.JEditorPane transactionsEP;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel CommentLabel;
    private javax.swing.JTextArea CommentTA;
    private javax.swing.JTabbedPane EmployeeTbP;
    private javax.swing.JLabel InvoiceLB;
    private javax.swing.JTextField InvoiceTF;
    private javax.swing.JButton OK;
    private com.toedter.calendar.JDateChooser SalaryDateChooser;
    private javax.swing.JScrollPane SalaryPaymentScP;
    private javax.swing.JTable SalaryPaymentTB;
    private javax.swing.JPanel TopLeftPanel;
    private javax.swing.JPanel TopRightPanel;
    private javax.swing.JPanel bottomButtonJP;
    private javax.swing.JPanel bottomJP;
    private javax.swing.JLabel leftDummyLabel;
    private javax.swing.JLabel rightDummyLabel;
    private javax.swing.JPanel topJP;
    // End of variables declaration//GEN-END:variables
    
}
