package com.exzoost.gui.transactions;
/*
 * TaxDialog.java
 *
 * Created on December 15, 2004, 1:43 PM
 */

import com.exzoost.database.Transaction;
import com.exzoost.gui.helper.GuiHelper;
import com.exzoost.gui.htmleditor.HTMLEditorManipulation;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author  knight
 */
public class OutcomeTransactionDialog extends javax.swing.JDialog {
    private Connection conn;
    private Transaction tr;
    /** Creates new form TaxDialog */
    public OutcomeTransactionDialog(java.awt.Frame parent, boolean modal, 
            javax.swing.JEditorPane transactionsEP, Connection conn ) {
        super(parent, modal);
        this.conn = conn;
        tr = new Transaction( conn );
        initComponents();
        
        GuiHelper.setOnCenter((Window)this);
        
        this.transactionsEP = transactionsEP;
        
        //setup the default button
        getRootPane().setDefaultButton(OK);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        TopPanel = new javax.swing.JPanel();
        TopRightPanel = new javax.swing.JPanel();
        ChargesDateChooser = new com.toedter.calendar.JDateChooser();
        TopLeftPanel = new javax.swing.JPanel();
        InvoiceLB = new javax.swing.JLabel();
        InvoiceTF = new javax.swing.JTextField();
        BottomPanel = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        DummyLeftLabel = new javax.swing.JLabel();
        RightDummyLabel = new javax.swing.JLabel();
        TaxPanel = new javax.swing.JPanel();
        AmountLabel = new javax.swing.JLabel();
        AmountTF = new javax.swing.JTextField();
        CommentLabel = new javax.swing.JLabel();
        CommentArea = new javax.swing.JTextArea();
        TypeOutcomeLabel = new javax.swing.JLabel();
        OutcomeComboBox = new javax.swing.JComboBox();

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Outcome Dialog");
        TopPanel.setLayout(new java.awt.BorderLayout());

        TopRightPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        ChargesDateChooser.setPreferredSize(new java.awt.Dimension(151, 20));
        TopRightPanel.add(ChargesDateChooser);

        TopPanel.add(TopRightPanel, java.awt.BorderLayout.EAST);

        TopLeftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        InvoiceLB.setText("Invoice : ");
        TopLeftPanel.add(InvoiceLB);

        InvoiceTF.setColumns(12);
        TopLeftPanel.add(InvoiceTF);

        TopPanel.add(TopLeftPanel, java.awt.BorderLayout.WEST);

        getContentPane().add(TopPanel, java.awt.BorderLayout.NORTH);

        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        BottomPanel.add(Cancel);

        OK.setText("OK");
        OK.setPreferredSize(new java.awt.Dimension(75, 25));
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        BottomPanel.add(OK);

        getContentPane().add(BottomPanel, java.awt.BorderLayout.SOUTH);

        DummyLeftLabel.setText("     ");
        getContentPane().add(DummyLeftLabel, java.awt.BorderLayout.WEST);

        RightDummyLabel.setText("     ");
        getContentPane().add(RightDummyLabel, java.awt.BorderLayout.EAST);

        TaxPanel.setLayout(new java.awt.GridBagLayout());

        AmountLabel.setText("Amount of Payment : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        TaxPanel.add(AmountLabel, gridBagConstraints);

        AmountTF.setColumns(24);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        TaxPanel.add(AmountTF, gridBagConstraints);

        CommentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CommentLabel.setText("Comment : ");
        CommentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        TaxPanel.add(CommentLabel, gridBagConstraints);

        CommentArea.setColumns(24);
        CommentArea.setLineWrap(true);
        CommentArea.setRows(5);
        CommentArea.setWrapStyleWord(true);
        CommentArea.setBorder(new javax.swing.border.EtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        TaxPanel.add(CommentArea, gridBagConstraints);

        TypeOutcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TypeOutcomeLabel.setText("Type of Charges : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        TaxPanel.add(TypeOutcomeLabel, gridBagConstraints);

        OutcomeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Electric", "Water", "Telephone", "Other" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        TaxPanel.add(OutcomeComboBox, gridBagConstraints);

        getContentPane().add(TaxPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        String invoice = InvoiceTF.getText().trim();
        String comment = CommentArea.getText();
        int amount = 0;
        
            
        if(invoice.trim().equals("")) {
            JOptionPane.showMessageDialog( null, "Please insert the invoice text field! ", 
                    "Warning", JOptionPane.WARNING_MESSAGE );
            InvoiceTF.requestFocusInWindow();
            return;
        }
        
        try {
            amount = Integer.parseInt(AmountTF.getText()); 
        }
        catch( NumberFormatException nfe ) {
            JOptionPane.showMessageDialog( null, "Please insert the amount text field " +
                    "with number! ", 
                    "Warning", JOptionPane.WARNING_MESSAGE );
            AmountTF.requestFocusInWindow();
            return;
        }
        
        String outcome = "";
        if(( (String)OutcomeComboBox.getSelectedItem()).equals("Water"))
            outcome = "Air";
        else if(( (String)OutcomeComboBox.getSelectedItem()).equals("Electric"))
            outcome = "Listrik";
        else if(( (String)OutcomeComboBox.getSelectedItem()).equals("Telephone"))
            outcome = "Telepon";
        else if(( (String)OutcomeComboBox.getSelectedItem()).equals("Other"))
            outcome = "Lain-lain";
        
        boolean result = tr.OutcomeTransaction( invoice, 
                new java.sql.Date(ChargesDateChooser.getDate().getTime()), 
                amount, outcome, comment );
        
        if(transactionsEP!=null
                &&result) {
            HTMLEditorManipulation htmlem = new HTMLEditorManipulation( transactionsEP, conn );
            htmlem.HTMLOutcomeDialog( InvoiceTF.getText().trim() );
        }
        
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutcomeTransactionDialog(new javax.swing.JFrame(), true, null, null).setVisible(true);
            }
        });
    }
    
    private javax.swing.JEditorPane transactionsEP;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JTextField AmountTF;
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton Cancel;
    private com.toedter.calendar.JDateChooser ChargesDateChooser;
    private javax.swing.JTextArea CommentArea;
    private javax.swing.JLabel CommentLabel;
    private javax.swing.JLabel DummyLeftLabel;
    private javax.swing.JLabel InvoiceLB;
    private javax.swing.JTextField InvoiceTF;
    private javax.swing.JButton OK;
    private javax.swing.JComboBox OutcomeComboBox;
    private javax.swing.JLabel RightDummyLabel;
    private javax.swing.JPanel TaxPanel;
    private javax.swing.JPanel TopLeftPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel TopRightPanel;
    private javax.swing.JLabel TypeOutcomeLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    
}
