/*
 * SearchInventoryDialog.java
 *
 * Created on November 14, 2004, 8:32 AM
 */

package com.exzoost.gui.inventory;

import com.exzoost.database.InventoryDB;
import com.exzoost.gui.helper.GuiHelper;
import com.exzoost.gui.maingui.MainGUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.sql.Connection;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  knight
 */
public class SearchInventoryDialog extends javax.swing.JDialog {
    private String place;
    private Connection conn;
    /** Creates new form SearchInventoryDialog */
    public SearchInventoryDialog(java.awt.Frame parent, boolean modal, 
            JTable table, String place, Connection conn ) {
        super(parent, modal);
        initComponents();
        this.conn = conn;
        
        GuiHelper.setOnCenter((Window)this);
        
        this.table = table;
        this.place = place;
        
        //setup default button
        getRootPane().setDefaultButton(Find);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        bottomJP = new javax.swing.JPanel();
        Close = new javax.swing.JButton();
        Find = new javax.swing.JButton();
        topJP = new javax.swing.JPanel();
        leftJP = new javax.swing.JPanel();
        rightJP = new javax.swing.JPanel();
        mainJP = new javax.swing.JPanel();
        ItemCodeLabel = new javax.swing.JLabel();
        ItemCodeTF = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        BuyingLessLabel = new javax.swing.JLabel();
        BuyingLessTF = new javax.swing.JTextField();
        BuyingMoreLabel = new javax.swing.JLabel();
        BuyingMoreTF = new javax.swing.JTextField();
        SaleLessLabel = new javax.swing.JLabel();
        SaleMoreLabel = new javax.swing.JLabel();
        SaleLessTF = new javax.swing.JTextField();
        SaleMoreTF = new javax.swing.JTextField();
        ProducerLabel = new javax.swing.JLabel();
        ProducerTF = new javax.swing.JTextField();
        QuantityLessThanLabel = new javax.swing.JLabel();
        QuantityLessThanTF = new javax.swing.JTextField();
        QuantityMoreThanLabel = new javax.swing.JLabel();
        QuantityMoreThanTF = new javax.swing.JTextField();
        SuplierLabel = new javax.swing.JLabel();
        SuplierTF = new javax.swing.JTextField();
        CategoryLabel = new javax.swing.JLabel();
        CategoryTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Items");
        bottomJP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        bottomJP.add(Close);

        Find.setText("Find");
        Find.setMaximumSize(new java.awt.Dimension(69, 25));
        Find.setMinimumSize(new java.awt.Dimension(69, 25));
        Find.setPreferredSize(new java.awt.Dimension(69, 25));
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });

        bottomJP.add(Find);

        getContentPane().add(bottomJP, java.awt.BorderLayout.SOUTH);

        getContentPane().add(topJP, java.awt.BorderLayout.NORTH);

        getContentPane().add(leftJP, java.awt.BorderLayout.WEST);

        getContentPane().add(rightJP, java.awt.BorderLayout.EAST);

        mainJP.setLayout(new java.awt.GridBagLayout());

        mainJP.setBorder(new javax.swing.border.TitledBorder("Item"));
        ItemCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ItemCodeLabel.setText("Item Code Contains : ");
        ItemCodeLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(ItemCodeLabel, gridBagConstraints);

        ItemCodeTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(ItemCodeTF, gridBagConstraints);

        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NameLabel.setText("Name Contains : ");
        NameLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(NameLabel, gridBagConstraints);

        NameTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(NameTF, gridBagConstraints);

        BuyingLessLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BuyingLessLabel.setText("Buying Price Less Than : ");
        BuyingLessLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(BuyingLessLabel, gridBagConstraints);

        BuyingLessTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(BuyingLessTF, gridBagConstraints);

        BuyingMoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BuyingMoreLabel.setText("Buying Price More Than : ");
        BuyingMoreLabel.setMaximumSize(new java.awt.Dimension(154, 15));
        BuyingMoreLabel.setMinimumSize(new java.awt.Dimension(154, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(BuyingMoreLabel, gridBagConstraints);

        BuyingMoreTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(BuyingMoreTF, gridBagConstraints);

        SaleLessLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SaleLessLabel.setText("Sale Price Less Than : ");
        SaleLessLabel.setMaximumSize(new java.awt.Dimension(154, 15));
        SaleLessLabel.setMinimumSize(new java.awt.Dimension(154, 15));
        SaleLessLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(SaleLessLabel, gridBagConstraints);

        SaleMoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SaleMoreLabel.setText("Sale Price More Than : ");
        SaleMoreLabel.setMaximumSize(new java.awt.Dimension(154, 15));
        SaleMoreLabel.setMinimumSize(new java.awt.Dimension(154, 15));
        SaleMoreLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(SaleMoreLabel, gridBagConstraints);

        SaleLessTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(SaleLessTF, gridBagConstraints);

        SaleMoreTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(SaleMoreTF, gridBagConstraints);

        ProducerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ProducerLabel.setText("Producer Contains : ");
        ProducerLabel.setMaximumSize(new java.awt.Dimension(154, 15));
        ProducerLabel.setMinimumSize(new java.awt.Dimension(154, 15));
        ProducerLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(ProducerLabel, gridBagConstraints);

        ProducerTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(ProducerTF, gridBagConstraints);

        QuantityLessThanLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        QuantityLessThanLabel.setText("Quantity Less Than : ");
        QuantityLessThanLabel.setMaximumSize(new java.awt.Dimension(154, 15));
        QuantityLessThanLabel.setMinimumSize(new java.awt.Dimension(154, 15));
        QuantityLessThanLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(QuantityLessThanLabel, gridBagConstraints);

        QuantityLessThanTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(QuantityLessThanTF, gridBagConstraints);

        QuantityMoreThanLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        QuantityMoreThanLabel.setText("Quantity More Than : ");
        QuantityMoreThanLabel.setMaximumSize(new java.awt.Dimension(154, 15));
        QuantityMoreThanLabel.setMinimumSize(new java.awt.Dimension(154, 15));
        QuantityMoreThanLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(QuantityMoreThanLabel, gridBagConstraints);

        QuantityMoreThanTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(QuantityMoreThanTF, gridBagConstraints);

        SuplierLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SuplierLabel.setText("Suplier Contains : ");
        SuplierLabel.setMaximumSize(new java.awt.Dimension(154, 15));
        SuplierLabel.setMinimumSize(new java.awt.Dimension(154, 15));
        SuplierLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(SuplierLabel, gridBagConstraints);

        SuplierTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(SuplierTF, gridBagConstraints);

        CategoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CategoryLabel.setText("Category Contains : ");
        CategoryLabel.setMaximumSize(new java.awt.Dimension(154, 15));
        CategoryLabel.setMinimumSize(new java.awt.Dimension(154, 15));
        CategoryLabel.setPreferredSize(new java.awt.Dimension(157, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(CategoryLabel, gridBagConstraints);

        CategoryTF.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        mainJP.add(CategoryTF, gridBagConstraints);

        getContentPane().add(mainJP, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        //get data from text field
        String name = NameTF.getText().trim();
        String itemcode = ItemCodeTF.getText().trim();
        String buyingless = BuyingLessTF.getText().trim();
        String buyingmore = BuyingMoreTF.getText().trim();
        String saleless = SaleLessTF.getText().trim();
        String salemore = SaleMoreTF.getText().trim();
        String producer = ProducerTF.getText().trim();
        String quantityless = QuantityLessThanTF.getText().trim();
        String quantitymore = QuantityMoreThanTF.getText().trim();
        String suplier = SuplierTF.getText().trim();
        String category = CategoryTF.getText().trim();
        
        if(name.equals("")) 
            name = null;
        
        if(itemcode.equals(""))
            itemcode = null;
        
        if(buyingless.equals(""))
            buyingless = null;
        
        if(buyingmore.equals(""))
            buyingmore = null;
        
        if(saleless.equals(""))
            saleless = null;
        
        if(salemore.equals(""))
            salemore = null;
        
        if(producer.equals(""))
            producer = null;
        
        if(quantityless.equals(""))
            quantityless = null;
        
        if(quantitymore.equals(""))
            quantitymore = null;
        
        if(suplier.equals(""))
            suplier = null;
        
        if(category.equals(""))
            category = null;
        
        InventoryDB st = new InventoryDB( conn );
        st.searchItem( table, place, category, name, itemcode, buyingless, buyingmore, saleless,
                salemore, producer, suplier, quantityless, quantitymore );
        
        dispose();
    }//GEN-LAST:event_FindActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        dispose();
    }//GEN-LAST:event_CloseActionPerformed
    
    
    private javax.swing.JTable table;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuyingLessLabel;
    private javax.swing.JTextField BuyingLessTF;
    private javax.swing.JLabel BuyingMoreLabel;
    private javax.swing.JTextField BuyingMoreTF;
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.JTextField CategoryTF;
    private javax.swing.JButton Close;
    private javax.swing.JButton Find;
    private javax.swing.JLabel ItemCodeLabel;
    private javax.swing.JTextField ItemCodeTF;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTF;
    private javax.swing.JLabel ProducerLabel;
    private javax.swing.JTextField ProducerTF;
    private javax.swing.JLabel QuantityLessThanLabel;
    private javax.swing.JTextField QuantityLessThanTF;
    private javax.swing.JLabel QuantityMoreThanLabel;
    private javax.swing.JTextField QuantityMoreThanTF;
    private javax.swing.JLabel SaleLessLabel;
    private javax.swing.JTextField SaleLessTF;
    private javax.swing.JLabel SaleMoreLabel;
    private javax.swing.JTextField SaleMoreTF;
    private javax.swing.JLabel SuplierLabel;
    private javax.swing.JTextField SuplierTF;
    private javax.swing.JPanel bottomJP;
    private javax.swing.JPanel leftJP;
    private javax.swing.JPanel mainJP;
    private javax.swing.JPanel rightJP;
    private javax.swing.JPanel topJP;
    // End of variables declaration//GEN-END:variables
    
}
