/*
 * AddSellerDialog.java
 *
 * Created on December 17, 2004, 1:59 PM
 */

package com.exzoost.gui.producer;

import com.exzoost.database.ProducerDB;
import com.exzoost.database.SellerDB;
import com.exzoost.gui.helper.GuiHelper;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import com.exzoost.database.InventoryDB;
import java.sql.Connection;
/**
 *
 * @author  knight
 */
public class AddProducerDialog extends javax.swing.JDialog {
    private Connection conn;
    /** Creates new form AddSellerDialog */
    public AddProducerDialog(java.awt.Frame parent, boolean modal, 
            JTable table, Connection conn ) {
        super(parent, modal);
        this.conn = conn;
        initComponents();
        
        GuiHelper.setOnCenter((Window)this);
        
        this.table = table;
        
        //setup default button
        getRootPane().setDefaultButton(OK);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        BottomPanel = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        DummyTopLabel = new javax.swing.JLabel();
        LeftDummyLabel = new javax.swing.JLabel();
        RightDummyLabel = new javax.swing.JLabel();
        SellerPanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        AddressTA = new javax.swing.JTextArea();
        TelephoneLabel = new javax.swing.JLabel();
        TelephoneTF = new javax.swing.JTextField();
        CommentLabel = new javax.swing.JLabel();
        CommentTA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Producer");
        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        BottomPanel.add(Cancel);

        OK.setText("OK");
        OK.setPreferredSize(new java.awt.Dimension(75, 25));
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        BottomPanel.add(OK);

        getContentPane().add(BottomPanel, java.awt.BorderLayout.SOUTH);

        DummyTopLabel.setText("                ");
        getContentPane().add(DummyTopLabel, java.awt.BorderLayout.NORTH);

        LeftDummyLabel.setText("     ");
        getContentPane().add(LeftDummyLabel, java.awt.BorderLayout.WEST);

        RightDummyLabel.setText("     ");
        getContentPane().add(RightDummyLabel, java.awt.BorderLayout.EAST);

        SellerPanel.setLayout(new java.awt.GridBagLayout());

        SellerPanel.setBorder(new javax.swing.border.TitledBorder("Producer"));
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NameLabel.setText("* Name : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        SellerPanel.add(NameLabel, gridBagConstraints);

        NameTF.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        SellerPanel.add(NameTF, gridBagConstraints);

        AddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AddressLabel.setText("Address : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        SellerPanel.add(AddressLabel, gridBagConstraints);

        AddressTA.setColumns(12);
        AddressTA.setLineWrap(true);
        AddressTA.setRows(4);
        AddressTA.setWrapStyleWord(true);
        AddressTA.setBorder(new javax.swing.border.EtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        SellerPanel.add(AddressTA, gridBagConstraints);

        TelephoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TelephoneLabel.setText("Telephone : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        SellerPanel.add(TelephoneLabel, gridBagConstraints);

        TelephoneTF.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        SellerPanel.add(TelephoneTF, gridBagConstraints);

        CommentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CommentLabel.setText("Comment : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        SellerPanel.add(CommentLabel, gridBagConstraints);

        CommentTA.setColumns(16);
        CommentTA.setLineWrap(true);
        CommentTA.setRows(8);
        CommentTA.setTabSize(4);
        CommentTA.setWrapStyleWord(true);
        CommentTA.setBorder(new javax.swing.border.EtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        SellerPanel.add(CommentTA, gridBagConstraints);

        jLabel1.setText("Fields marked with an asterisk * are required.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        SellerPanel.add(jLabel1, gridBagConstraints);

        getContentPane().add(SellerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        //gather information from dialog text field
        String name = NameTF.getText().trim();
        String phone = TelephoneTF.getText();
        String address = AddressTA.getText().trim();
        String comment = CommentTA.getText();
        
        //the name field must not be null
        if(name.equals("")) {
            JOptionPane.showMessageDialog(null,"Please insert the Name Text Field!", 
                    "Warning", JOptionPane.WARNING_MESSAGE );
            NameTF.requestFocusInWindow();
            return;
        }
        
        //must use the seller class
        ProducerDB st = new ProducerDB(conn);
        boolean result = st.insertProducer( table, name, address, phone, comment );
        
        //error inserting producer
        if(!result)
            JOptionPane.showMessageDialog(null,"Error adding producer data! See log file " +
                    "for detail!", "Warning", JOptionPane.WARNING_MESSAGE );
        
        //free the resources
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProducerDialog(new javax.swing.JFrame(), true, null, 
                        null).setVisible(true);
            }
        });
    }
    
    private javax.swing.JTable table;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextArea AddressTA;
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel CommentLabel;
    private javax.swing.JTextArea CommentTA;
    private javax.swing.JLabel DummyTopLabel;
    private javax.swing.JLabel LeftDummyLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton OK;
    private javax.swing.JLabel RightDummyLabel;
    private javax.swing.JPanel SellerPanel;
    private javax.swing.JLabel TelephoneLabel;
    private javax.swing.JTextField TelephoneTF;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
